environment:
  matrix:
    - PYTHON: "C:/Python27"

clone_folder: c:\projects\sphinx-docfx-yaml

install:
  # Nuget
  - nuget install uref -Prerelease -Source https://www.myget.org/F/docfx-dev/api/v3/index.json -ExcludeVersion -OutputDirectory c:\projects\docfx.uref
  # .NET
  - cinst docfx -y
  # Python
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/pip.exe -q -q -q install tox sphinx msrest msrestazure sphinx_rtd_theme ."

build_script:
  - cd c:\projects\sphinx-docfx-yaml\docs
  - "git clone https://github.com/ericholscher/azure-sdk-for-python/"
  - cd azure-sdk-for-python
  - python setup.py -q install 
  - cd doc
  - "%PYTHON%/Scripts/sphinx-build.exe -b html -d _build/doctrees . _build/html"
  - docfx build

artifacts:
  - path: 'docs/azure-sdk-for-python/doc/'
